{
  "formatVersion": "1.1",
  "component": {
    "group": "com.othento",
    "module": "othento-core",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "othento-core-0.1.3.aar",
          "url": "othento-core-0.1.3.aar",
          "size": 1929058,
          "sha512": "16cfeb3aa336b350c77be1bdebaf4f104c032063467cd880a211cc0ae9320028d7cde9171a49caea8157d19c1b533af0bbd764b7e9b6ef5bfc63842eda723fc8",
          "sha256": "2cba73ce9a85fc6444e7f8e8e124bd4f034308ec0b723dc3310c3594b9137925",
          "sha1": "29df207f6f8f53bf33d55d76ed540d9fd4d4b02a",
          "md5": "ba20e2baaa78072da16146d973b611f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.pqpo",
          "module": "SmartCropper",
          "version": {
            "requires": "v2.1.4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.7"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.13.35"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.amplifyframework.ui",
          "module": "liveness",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "othento-core-0.1.3.aar",
          "url": "othento-core-0.1.3.aar",
          "size": 1929058,
          "sha512": "16cfeb3aa336b350c77be1bdebaf4f104c032063467cd880a211cc0ae9320028d7cde9171a49caea8157d19c1b533af0bbd764b7e9b6ef5bfc63842eda723fc8",
          "sha256": "2cba73ce9a85fc6444e7f8e8e124bd4f034308ec0b723dc3310c3594b9137925",
          "sha1": "29df207f6f8f53bf33d55d76ed540d9fd4d4b02a",
          "md5": "ba20e2baaa78072da16146d973b611f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "othento-core-0.1.3-sources.jar",
          "url": "othento-core-0.1.3-sources.jar",
          "size": 433188,
          "sha512": "924079c335774a0ae06406550fd7430a0969dbcb82dba28fa98e8c0bea71661831b8048849d7911ce5f8a5ee2491bf20545152a19e1132df5a79a7f854a1c6b7",
          "sha256": "4816d4c0897fa474896fb667e165687c528cd189fc6c47e3ec57a361a8c567f1",
          "sha1": "4ddce45698dd6d14b7f4d64d95cbed2be35fc973",
          "md5": "83c45618ea83e4cf9ca16ba4ca52b98a"
        }
      ]
    }
  ]
}
