{
  "formatVersion": "1.1",
  "component": {
    "group": "com.othento",
    "module": "othento-core",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "othento-core-0.1.2.aar",
          "url": "othento-core-0.1.2.aar",
          "size": 1929059,
          "sha512": "fd2c4997a17a489e7e7149c6e94803af475fa1881b89ccea3834b507bdf4135ed75068e10cc82b697b326bc9fca567e01e99cf5d36b79c3973da6f94a80f7ee0",
          "sha256": "4a5c05b06bb1aa361a8be6fa73a2874e552d2c1ab41ea38e5a6993a6a5b28b30",
          "sha1": "ca0aa2aada10b9d48d64f1ebb88bf2bcac001a34",
          "md5": "391fde84ecd73a323bb8ed060995fac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.pqpo",
          "module": "SmartCropper",
          "version": {
            "requires": "v2.1.4"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "text-recognition",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.7"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.13.35"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.amplifyframework.ui",
          "module": "liveness",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "othento-core-0.1.2.aar",
          "url": "othento-core-0.1.2.aar",
          "size": 1929059,
          "sha512": "fd2c4997a17a489e7e7149c6e94803af475fa1881b89ccea3834b507bdf4135ed75068e10cc82b697b326bc9fca567e01e99cf5d36b79c3973da6f94a80f7ee0",
          "sha256": "4a5c05b06bb1aa361a8be6fa73a2874e552d2c1ab41ea38e5a6993a6a5b28b30",
          "sha1": "ca0aa2aada10b9d48d64f1ebb88bf2bcac001a34",
          "md5": "391fde84ecd73a323bb8ed060995fac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "othento-core-0.1.2-sources.jar",
          "url": "othento-core-0.1.2-sources.jar",
          "size": 433031,
          "sha512": "28d6769b5c969948677241c711d4da2496af50643ce8da07a2eb6bb32a72ab0f33477b67921bdf4f10496cc16cc1fc9a69b2c9800cb545832f6b2b367035989f",
          "sha256": "9724a7d41d367de972541a530c529b0721a3e9d95a3c7522691eb4e36c0e45fd",
          "sha1": "e545f4d7713eb134317904f1beba07af9b5d93f6",
          "md5": "2e6236f178facca7d783e596a0b17794"
        }
      ]
    }
  ]
}
